name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Greet with Secret
      run: |
        echo Here is my secret greeting...
        echo $GREET
        echo {{ secret.GREET }}
        echo ${{ secret.GREET }}
        echo ${{ secrets.GREET }}
        echo ${{ env.GREET }}
