name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: Greet with Secret
      env:
        HI: ${{ secrets.GREET }}
        CODE: ${{ secrets.CODEWORD }}
      run: |
        echo Here is my secret greeting...;
        python -c "import os; print(os.environ['HI'], len(os.environ['HI']), os.environ['HI'].lower());"
        python -c "import os; print(os.environ['CODE'], len(os.environ['CODE']), os.environ['CODE'].lower());"
